services:
  feedback-traefik:
    image: traefik:v3.6.2
    container_name: feedback-traefik--staging
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    security_opt:
      - no-new-privileges:true
    command:
      - "--global.checkNewVersion=true"
      - "--global.sendAnonymousUsage=false"

      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.file.directory=/rules"
      - "--providers.file.watch=true" # Only works on top level files

      - "--api.dashboard=true"
      - "--api.insecure=true"

      - "--log=true"
      - "--log.level=DEBUG"
      - "--accessLog=true"
      - "--accessLog.filePath=/var/log/traefik/access.log"

      - "--entrypoints.web-secure.address=:443"
      - "--entrypoints.web-secure.http.tls=true"
      - "--entrypoints.web-secure.http.tls.options=tls-opts@file"
      - "--entrypoints.web-secure.http.middlewares=middleware-secure-headers@file"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=web-secure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      # - "--serversTransport.insecureSkipVerify=true" 
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # - "./staging/rules/dynamic.yml:/rules/dynamic.yml:ro"
      - "./staging/rules:/rules"
      - "./staging/logs:/var/log/traefik"
      - "./staging/certs:/certs"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.services.dashboard.loadbalancer.server.port=8080"

volumes:
  letsencrypt:
